
# --- Shell settings ---

shell nu

# --- Font settings ---

font_family ComicShannsMono Nerd Font
font_size   12.0
modify_font cell_width 103%

# --- Keymaps ---

# Launch new window in current cwd with ctrl + alt + enter
map ctrl+alt+enter launch --cwd=current --type=os-window

